version: '3'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: incunabula
      POSTGRES_PASSWORD: pasuwado
      POSTGRES_DB: incunabula
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
