default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: incunabula_development
  host: 127.0.0.1
  port: 15432
  username: incunabula
  password: pasuwado

test:
  <<: *default
  database: incunabula_test
  host: 127.0.0.1
  port: 15432
  username: incunabula
  password: pasuwado

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
