name: RSpec

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: 'postgres:15'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pasuwado
          POSTGRES_DB: incunabula_test
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-start-period 5s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: 'postgres://postgres@localhost:5432/incunabula_test'
      DATABASE_PASSWORD: 'pasuwado'
      RAILS_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Force rewrite .ruby-version and Gemfile
      - run: |
          echo '3.4' > .ruby-version
          sed -i "/^ruby '/d" Gemfile
        shell: bash

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Ridgepole
        run: |
          bundle exec ridgepole -c config/database.yml -E test -f db/Schemafile --apply

      - name: RSpec
        run: |
          bundle exec rspec
